---
title: "Mini-Project 2: Federal Election 2012"
author: "Shuli Hu, Karina Huang, Iris Dong"
date: "October 31, 2017"
output: html_document
---

###Issue

a short paragraph introducing what we are looking at

```{r, warning=FALSE, message=FALSE}
#load packages 
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(grid)
library(gridExtra)
```

```{r}
#load dataset
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, warning=FALSE, message=FALSE}
#Shuli rewrite chunk "Karina 10/29/17 #1 #2"

#create two lists of transaction type and entity type
entity_type_list = c("CAN", "CCM", "COM", "IND", "ORG", "PAC", "PTY")

#wrangling data in contributions
contributions1 <- contributions %>%
  filter(transaction_type == "24E" | transaction_type == "24A") %>%
  filter(entity_type != "") %>%
  group_by(cand_id) %>%
  summarise(pro.CAN = sum(transaction_amt[entity_type == "CAN" & transaction_type == "24E"]),
            pro.CCM = sum(transaction_amt[entity_type == "CCM" & transaction_type == "24E"]),
            pro.COM = sum(transaction_amt[entity_type == "COM" & transaction_type == "24E"]),
            pro.IND = sum(transaction_amt[entity_type == "IND" & transaction_type == "24E"]),
            pro.ORG = sum(transaction_amt[entity_type == "ORG" & transaction_type == "24E"]),
            pro.PAC = sum(transaction_amt[entity_type == "PAC" & transaction_type == "24E"]),
            pro.PTY = sum(transaction_amt[entity_type == "PTY" & transaction_type == "24E"]),
            con.Can = sum(transaction_amt[entity_type == "CAN" & transaction_type == "24A"]),
            con.CCM = sum(transaction_amt[entity_type == "CCM" & transaction_type == "24A"]),
            con.COM = sum(transaction_amt[entity_type == "COM" & transaction_type == "24A"]),
            con.IND = sum(transaction_amt[entity_type == "IND" & transaction_type == "24A"]),
            con.ORG = sum(transaction_amt[entity_type == "ORG" & transaction_type == "24A"]),
            con.PAC = sum(transaction_amt[entity_type == "PAC" & transaction_type == "24A"]),
            con.PTY = sum(transaction_amt[entity_type == "PTY" & transaction_type == "24A"]))

candidates1 <- candidates %>% ## New candidate dataset
  filter(cand_id %in% c(contributions1$cand_id)) %>% ## get the cand_id exists in both candidates and contributions1 
  select(cand_id:cand_office, cand_ici:cand_status) 

 
#create two lists of pro.type and con.type
pro.type <- c()
con.type <- c()
i=1
while(i<=length(entity_type_list)) {
       a <- paste("pro", entity_type_list[i], sep=".")
       b <- paste("con", entity_type_list[i], sep=".")
       pro.type <- c(pro.type, a)
       con.type <- c(con.type, b)
       i=i+1
 }

#join tables candidates and contributions by candidate ID
election <- full_join(candidates1, contributions1, by = "cand_id") %>% 
  mutate(pro.sum = pro.CAN+pro.CCM+pro.COM+pro.IND+pro.ORG+pro.PAC+pro.PTY, 
          con.sum = con.Can+con.CCM+con.COM+con.IND+con.ORG+con.PAC+con.PTY) %>%
  group_by(cand_party_affiliation) %>%
  summarise(pro.CAN = sum(pro.CAN), pro.CCM = sum(pro.CCM), pro.COM = sum(pro.COM), 
            pro.IND = sum(pro.IND), pro.ORG = sum(pro.ORG), pro.PAC = sum(pro.PAC),
            pro.PTY = sum(pro.PTY), 
            con.CAN = sum(con.Can), con.CCM = sum(con.CCM), con.COM = sum(con.COM),
            con.IND = sum(con.IND), con.ORG = sum(con.ORG), con.PAC = sum(con.PAC),
            con.PTY = sum(con.PTY), pro.sum = sum(pro.sum), con.sum = sum(con.sum)) %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP") %>%
  gather("type", "amount",pro.CAN:con.PTY) %>%
  mutate(transaction.type = ifelse(type %in% c(pro.type), "pro", "con"),
         entity.type = ifelse(type %in% "pro.CAN" | type %in% "con.CAN", "CAN", 
                              ifelse(type %in% "pro.CCM" | type %in% "con.CCM", "CCM", 
                                     ifelse(type %in% "pro.COM" | type %in% "con.COM", "COM", 
                                            ifelse(type %in% "pro.IND" | type %in% "con.IND", "IND", 
                                                   ifelse(type %in% "pro.ORG" | type %in% "con.ORG", "ORG", 
                                                          ifelse(type %in% "pro.PAC" | type %in% "con.PAC", "PAC",
                                                                 ifelse(type %in% "pro.PTY" | type %in% "con.PTY", "PTY", type)))))))) %>%
  select(-type) %>%
  spread(transaction.type, amount) %>%
  select(-pro.sum, -con.sum) %>%
  gather("transaction.type", "amount", con:pro)
```

###describe the table

```{r, warning=FALSE, message=FALSE}
#Shuli rewrite 10/31/2017 morning

#join tables election
election2 <- election %>%
  group_by(cand_party_affiliation, entity.type) %>%
  summarise(party_entity_total = sum(amount)) #for each party*entity the total amount of transactions

election_total <- left_join(election, election2, by = c("cand_party_affiliation", "entity.type"))

#for only entity type "ORG""
election_org_only <- election2 %>%
  filter(entity.type == "ORG")

election_non_org <- election2 %>%
  filter(!entity.type == "ORG")

print(election_org_only)
party_name <- c(DEM="Democratic",
                REP="Republican")
```


```{r}
print(election2)
summary(election_org_only)
```


###describe the plot

The percentage distribution of contributions

```{r, warning=FALSE, message=FALSE, fig.width=10, fig.height=8, echo=FALSE}
#plot
#percentage distribution of contributions
ggplot(election_total, aes(x = entity.type, y = amount/party_entity_total*100, fill=transaction.type, width = 0.7)) + 
  geom_bar(stat = "identity", alpha=0.8) + 
  facet_grid(cand_party_affiliation~.,labeller=as_labeller(party_name)) +
  labs(title = "Distribution of Contributions \nby Party and Entity Type",x="Entity Type", y="Contributions (%)") +
  theme(plot.title=element_text(size = 18, 
                                face="bold", 
                                family="Helvetica", 
                                hjust=0.5,
                                margin = margin(t=0,r=0,b=20,l=20)), 
        axis.title = element_text(face="bold",size = 15),
        axis.title.x = element_text(margin = margin(t=20,r=0,b=0,l=0)),
        axis.title.y = element_text(margin = margin(t=0,r=20,b=0,l=0)),
        strip.text.y = element_text(face="bold",size = 13),
        strip.background =element_rect(fill="white"),
        legend.title = element_text(face="bold",size=15),
        legend.text = element_text(size=10),
        panel.border=element_blank(), 
        panel.grid=element_blank(),
        panel.margin=unit(2,"lines"))+
  scale_fill_discrete(name="Transaction Type",
                         breaks=c("con", "pro"),
                         labels=c("Opposing election of candidate", "Advocating election of candidate"))
```

###describe the plot

```{r, warning=FALSE, message=FALSE, fig.width=10, fig.height=8, echo=FALSE}
#amount distribution of contributions
p2 <- ggplot(election_non_org, aes(x = entity.type, y = party_entity_total/1000000)) + 
  geom_bar(stat = "identity", 
           alpha = 0.8, fill="blue") + 
  facet_grid(.~cand_party_affiliation,
             labeller=as_labeller(party_name)) +
  labs(title = "Contributions by Party and Entity Type (Non-ORG)",x="Entity Type", y="Amount of Contributions \n(in 'mil USD)", fill="Transaction Type") +
  geom_text(aes(label=round(party_entity_total/1000000, digits=3)), vjust=-0.3, color="black", size=3.5)+
   scale_y_continuous(limits = c(0, 15),
                      breaks = c(0, 5, 12), 
                     labels = c("0", "5", "12"))+
  scale_fill_discrete(name="Transaction Type",
                         breaks=c("con", "pro"),
                         labels=c("Opposing election of candidate", "Advocating election of candidate"))+
  theme(plot.title=element_text(size= 18, 
                                face="bold", 
                                family="Helvetica", 
                                hjust=0.5,
                                margin = margin(t=0,r=0,b=20,l=20)),
        axis.title = element_text(face="bold",size = 15),
        axis.title.x = element_text(margin = margin(t=20,r=0,b=0,l=0)),
        axis.title.y = element_text(margin = margin(t=0,r=20,b=0,l=0)),
        strip.text.x = element_text(face="bold",size = 13),
        strip.background =element_rect(fill="white"),
        legend.title = element_text(face="bold",size=15),
        legend.text = element_text(size=10),
        panel.border=element_blank(), 
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank())
  

p3 <- ggplot(election_org_only, aes(x = entity.type, y = party_entity_total/1000000, width=0.15)) + 
  geom_bar(stat = "identity",
           alpha=0.8, 
           fill="blue") + 
  facet_grid(.~cand_party_affiliation,
             labeller=as_labeller(party_name)) +
  labs(title = "Contributions by Party and Entity Type (ORG)",x="Entity Type", y="Amount of Contributions \n(in ‘mil USD)", fill="Transaction Type") +
  geom_text(aes(label=round(party_entity_total/1000000, digits=3)), vjust=-0.3, color="black", size=3.5)+
   scale_y_continuous(limits = c(0,700),
                      breaks = c(0, 300, 600), 
                     labels = c("0", "300", "600"))+
  scale_fill_discrete(name="Transaction Type",
                         breaks=c("con", "pro"),
                         labels=c("Opposing election of candidate", "Advocating election of candidate"))+
  theme(plot.title=element_text(size=18, 
                                face="bold", 
                                family="Helvetica", 
                                hjust=0.5,
                                margin = margin(t=10,r=0,b=20,l=20)),
        axis.title = element_text(face="bold",size = 15),
        axis.title.x = element_text(margin = margin(t=20,r=0,b=0,l=0)),
        axis.title.y = element_text(margin = margin(t=0,r=20,b=0,l=0)),
        strip.text.x = element_text(face="bold",size = 13),
        strip.background =element_rect(fill="white"),
        legend.title = element_text(face="bold",size=15),
        legend.text = element_text(size=10),
        panel.border=element_blank(), 
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank())
 

grid.arrange(p2,p3)
```




















